owner: kyundothost
repo: status

sites:
  - name: Main API
    url: https://api.kyun.host/ping
    __dangerous__body_down_if_text_missing: 'pong'

status-website:
  cname: status.kyun.host
  name: Kyun Status
